spring.application.name=bff-atm
server.port=8083

ms-bank-legacy.url=http://localhost:8080
# 🔐 CONFIGURACIÓN SSL PARA BFF-ATM (8083)
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=banco_xyz

# 🔐 JWT CONFIGURATION
jwt.secret=4oPx8zNq7bT5rW1vK2dG6fY9lU3cX7eV2aJ8sD0qF3gR9wS5tV1uM4hN7bG3sF0pE9
jwt.expiration=3600000

# Configuración de Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Configuración de Resilience4j

# CIRCUIT BREAKER
# Cuántas llamadas seguidas va a evaluar
resilience4j.circuitbreaker.instances.msbankLegacyClient.sliding-window-size=5
# Si el 50% fallan, corta la conexión
resilience4j.circuitbreaker.instances.msbankLegacyClient.failure-rate-threshold=50
# Cuánto tiempo deja cortada la conexión dándole respiro al Core
resilience4j.circuitbreaker.instances.msbankLegacyClient.wait-duration-in-open-state=10s
# Llamadas de prueba para ver si el Core ya revivió
resilience4j.circuitbreaker.instances.msbankLegacyClient.permitted-number-of-calls-in-half-open-state=3

# REINTENTOS
# Maximo de reintentos
resilience4j.retry.instances.msbankLegacyClient.max-attempts=3
# Tiempo de espera entre reintentos
resilience4j.retry.instances.msbankLegacyClient.wait-duration=2s

# RATE LIMITER
resilience4j.ratelimiter.instances.msbankLegacyClient.limit-for-period=20
resilience4j.ratelimiter.instances.msbankLegacyClient.limit-refresh-period=1s
resilience4j.ratelimiter.instances.msbankLegacyClient.timeout-duration=0s

# TIMEOUTS HTTP REST CLIENT
ms-bank-legacy.connect-timeout=5000
ms-bank-legacy.read-timeout=5000
