spring.application.name=bff-web
server.port=8081

ms-bank-legacy.url=http://localhost:8080

# 🔐 CONFIGURACIÓN SSL PARA BFF-WEB (8081)
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=banco_xyz

# 🔐 JWT CONFIGURATION
jwt.secret=4oPx8zNq7bT5rW1vK2dG6fY9lU3cX7eV2aJ8sD0qF3gR9wS5tV1uM4hN7bG3sF0pE9
jwt.expiration=3600000
